### PR TITLE
Added support for SPICE over SSL

### PR DESCRIPTION
**Pull request by zyx0225**

### CODE REVIEW

**Comment by zyx0225** [comment]
Supported aSPICE:
src = https://github.com/zyx0225/remote-desktop-clients/tree/aSPICE
debug app = https://github.com/zyx0225/remote-desktop-clients/blob/aSPICE/eclipse_projects/bVNC/aSPICE-debug.apk?raw=true

**Comment by zyx0225** [comment]
The aSPICE code after modified as followed:
https://github.com/zyx0225/remote-desktop-clients/tree/aSPICE，
The author's source code:
https://github.com/iiordanov/remote-desktop-clients，
Using the author's souce code, what I got form compile is bVNC instead of aSPICE, in https://github.com/iiordanov/remote-desktop-clients/blob/master/BUILDING  the author give the way how to compile bVNC into aSPICE, that is the way how I successfully compile aSPICE

**Comment by zyx0225** [comment]
But I have no ide how to compile libspice.so and libgstreamer_android.so, so I copy lib document of freeaSPICE-3.7.7-final.apk, and compile aSPICE successfully.Howerve it only works while I rename the package name of aSPICE APP as the same name of the package of freeaSPICE-3.7.7-final.apk

**Comment by zyx0225** [comment]
ok, I'll change them

**Comment by zyx0225** [comment]
ok, I have fixed it
@jelkosz

**Comment by jelkosz** [comment]
@zyx0225 now it seems ok - please rebase and I will merge

**Comment by zyx0225** [comment]
@jelkosz I have rebased it

**Comment by zyx0225** [comment]
@jelkosz Thank you. I have fixed it.

**Comment by zyx0225** [comment]
@jelkosz I have fixed it

**Comment by jelkosz** [comment]
@zyx0225 one more problem I have faced after applying this patch - if I cluster drawer (left side) the "all clusters" than it fails on this exception:

7-03 07:57:02.453  28250-28250/org.ovirt.mobile.movirt D/AndroidRuntime﹕ Shutting down VM
07-03 07:57:02.474  28250-28250/org.ovirt.mobile.movirt E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.ovirt.mobile.movirt, PID: 28250
    java.lang.RuntimeException: java.lang.IllegalArgumentException: column 'version' does not exist
            at org.ovirt.mobile.movirt.model.EntityMapper.fromCursor(EntityMapper.java:22)
            at org.ovirt.mobile.movirt.ui.MainActivity.clusterDrawerItemClicked(MainActivity.java:292)
            at org.ovirt.mobile.movirt.ui.MainActivity_$3.onItemClick(MainActivity_.java:156)
            at android.widget.AdapterView.performItemClick(AdapterView.java:300)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1143)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3044)
            at android.widget.AbsListView$3.run(AbsListView.java:3833)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5312)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
     Caused by: java.lang.IllegalArgumentException: column 'version' does not exist
            at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:303)
            at org.ovirt.mobile.movirt.util.CursorHelper.getString(CursorHelper.java:16)
            at org.ovirt.mobile.movirt.model.Cluster.initFromCursorHelper(Cluster.java:88)
            at org.ovirt.mobile.movirt.model.BaseEntity.initFromCursor(BaseEntity.java:23)
            at org.ovirt.mobile.movirt.model.EntityMapper.fromCursor(EntityMapper.java:19)
            at org.ovirt.mobile.movirt.ui.MainActivity.clusterDrawerItemClicked(MainActivity.java:292)
            at org.ovirt.mobile.movirt.ui.MainActivity_$3.onItemClick(MainActivity_.java:156)
            at android.widget.AdapterView.performItemClick(AdapterView.java:300)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1143)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3044)
            at android.widget.AbsListView$3.run(AbsListView.java:3833)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5312)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

**Comment by zyx0225** [comment]
@jelkosz I have fixed it

**Pull request merged**
