### PR TITLE
added up button

### PR DESCRIPTION
**Pull request by suomiy**

### CODE REVIEW

**Comment by NoiseDoll** [comment]
@matobet `VmMigrateActivity` and `EditTriggersActivity`, they are kinda fullscreen dialogs. At first when I made Vm migrate view - it was a dialog, but later we decide that it would better to make it as an activity because AndroidAnnotation has bad support of dialogs. And as this two activities actually dialogs they don't need this top level stuff from MovirtActivity.

**Comment by matobet** [comment]
@NoiseDoll I see. Do you think these 2 activities would benefit from the action bar "UP" navigation?

**Comment by suomiy** [comment]
@matobet I made these two behave like back button, because it seems natural. That means you can get back to the vm which started that activity. I am not sure about camera and settings, if we need up button there. VmDetailActivity has up button.

**Comment by suomiy** [comment]
@matobet I couldn't move similar functionality to MovirtActivity because the behavior depends on that particular activity. I don't see many options how to reduce homeSelected() code duplicacy.

**Pull request merged**
