### PR TITLE
Add activate and maintenance actions for host details activity

### PR DESCRIPTION
**Pull request by zyx0225**
1.Add activate and maintenance actions for host details activity
2.Optimized actions display for vm and host details activity

### CODE REVIEW

**Comment by zyx0225** [comment]
ok, I'll fix it

**Comment by zyx0225** [comment]
I'll change it. Thank you :)

**Comment by matobet** [comment]
Created #68 for utilizing the existing Vm.Command enum.

**Comment by zyx0225** [comment]
I see Vm.Command enum.I'll try to utilize this.

**Comment by zyx0225** [comment]
Is the command right?
@jelkosz 
Vm.Command
```java
public enum Command {
        RUN(Status.DOWN, Status.PAUSED),
        STOP(Status.WAIT_FOR_LAUNCH, Status.UP, Status.POWERING_DOWN, Status.POWERING_UP,
                Status.REBOOT_IN_PROGRESS, Status.MIGRATING, Status.SUSPENDED, Status.PAUSED,
                Status.NOT_RESPONDING),
        SHUTDOWN(Status.UP),
        POWEROFF(Status.UP, Status.POWERING_UP, Status.POWERING_DOWN),
        REBOOT(Status.UP, Status.POWERING_UP),
        CONSOLE(Status.UP);

        private final List<Status> validStates;

        public List<Status> getValidStates() {
            return validStates;
        }

        Command(Status ...validStates) {
            this.validStates = Arrays.asList(validStates);
        }

        public boolean canExecute(Status status) {
            return validStates.contains(status);
        }
    }
```

Host.Command
```java
public enum Command {
        ACTIVATE(Status.MAINTENANCE, Status.ERROR, Status.PREPARING_FOR_MAINTENANCE,
                Status.NON_OPERATIONAL, Status.INSTALL_FAILED),
        DEACTIVATE(Status.UP, Status.ERROR, Status.NON_RESPONSIVE, Status.NON_OPERATIONAL,
                Status.INSTALL_FAILED, Status.DOWN);

        private final List<Status> validStates;

        public List<Status> getValidStates() {
            return validStates;
        }

        Command(Status ...validStates) {
            this.validStates = Arrays.asList(validStates);
        }

        public boolean canExecute(Status status) {
            return validStates.contains(status);
        }
    }
```

**Comment by jelkosz** [comment]
@zyx0225 
- the Host.Command is OK.
- the Vm.Command:
the CONSOLE has to have "PoweringUp, Up, RebootInProgress, PoweringDown, Paused"

And I think we don't use the "SHUTDOWN and POWEROFF so I would not let it there...

**Pull request merged**
