### PR TITLE
Use ViewPager and PagerTabStrip instead of ActionBar.Tab

### PR DESCRIPTION
**Pull request by zyx0225**

### CODE REVIEW

**Comment by jelkosz** [comment]
Well, this patch introduces the ViewPager to the main VM list only. I agree it looks much better than the previous ActionBar but it looks really strange to have one navigation when you are on the VM list screen and a different one when you are on VM details...

Could you please provide a similar patch enriching this support also to VM details? Or modify this one if you prefer.

But again, it is a very nice patch, thank you for contributing it!

**Comment by zyx0225** [comment]
The new patch enriching viewpage support also to VM details

**Comment by zyx0225** [comment]
I have fixed the error that "When you turn the device on main screen to change from/to landscape". However, "When accessing the sisks tab(strangely NIC related)" do not happen on my side, could you please describ what operation can cause this error :)

**Comment by jelkosz** [comment]
well, it happens to me all the time. The reproducer:
- open VM details
- swipe to the events (all fine)
- swipe to disks. Here for some reason the NicDetailFragment.refresh is executed and fails with the NPE pasted before. Maybe you can not reproduce it because of some race condition since the loadNicDetails() runs on background and in parallel the views can be injected (just guessing, maybe something different). But in any case, there are 2 problems:
- the refresh of nics is called before the nics are actually shown
- you trust that the views are already injected when they are not (to be on safe side you have to call the code touching injected views only from @AfterInject method)

**Comment by matobet** [comment]
Just a note, @jelkosz probably meant @AfterViews, the @AfterInject methods are called after general injections of @Ebeans and **before** the views are injected. To guarantee no views will be null please use a @AfterViews annotated method

**Comment by jelkosz** [comment]
@matobet yeah, extended typo :D

**Comment by jelkosz** [comment]
@zyx0225 not sure if you have seen the comments - to be on safe side mentioning your nick :)

**Comment by zyx0225** [comment]
I add Log function in function NicDetailFragment.displayListView, and then swipe to the events. However, while I swipe to disks, function NicDetailFragment is not called, and I have tried many times using 4.2 and 5.0 monitor   , and do not find NullPointerException. I add if condition in function displayListView and hope it would solve the NullPointerException problem :)

**Comment by jelkosz** [comment]
@zyx0225 hi, so after this patch I don't see the NPE issue anymore but a new one appeared in the details activity. Not exactly sure about the reproducer, but basically what you need to do to reproduce it is to turning the device and swiping around and than turning and swiping. After a short while you will start receiving:

GET request for "https://192.168.122.218:443/ovirt-engine/api/vms//nics" resulted in 404 (Not Found); invoking error handler

(e.g. the VM id is not there). Tried to reproduce this on the master branch and it worked well there.

**Comment by zyx0225** [comment]
@jelkosz I have fixed the error when turn the device on disks and nics screen to change from/to landscape.
Thank you :)

**Comment by jelkosz** [comment]
OK, after this change the patch looks nice and stable. Thank you for it!

So I have merged the pull request from cmd line and for some reason this did not get closed - closing by hand.

**Pull request closed without merging**
