### PR TITLE
Refactored all memory sizes/units

### PR DESCRIPTION
**Pull request by suomiy**

### CODE REVIEW

**Comment by suomiy** [comment]
I would be glad if somebody could test this on richer environment than mine

**Comment by mykaul** [comment]
@suomiy do you make the required distinction between MB and MiB ? 
See https://en.wikipedia.org/wiki/Mebibyte - this is especially important in storage.

**Comment by suomiy** [comment]
@mykaul yes this would be confusing. We should use IEC units instead. Thank you

**Comment by suomiy** [comment]
fixed in #179

**Pull request merged**
